version: "3"
services:
  ludo-frontend:
    image: ludo-frontend
    env_file: ./.env
    stdin_open: true
    environment:
      - REACT_APP_CLIENT_BASEURL=$REACT_APP_CLIENT_BASEURL
      - REACT_APP_CLIENT_URL=$REACT_APP_CLIENT_URL
      - REACT_APP_CLIENT_BASEURL_WS=$REACT_APP_CLIENT_BASEURL_WS
    ports:
      - "3000:3000"
