import { makeStyles } from "@material-ui/core";

export const optionsDrawerStyles = makeStyles((theme) => ({
  drawerPaper: {
    maxWidth: "555px",
    width: "100vw",
    minHeight: "45vh",
    borderTopLeftRadius: "1rem",
    borderTopRightRadius: "1rem",
    margin: "auto",
    [theme.breakpoints.down(600)]: {
      minHeight: "40vh",
    },
  },
  pascodeTxt: {
    textAlign: "center",
    margin: "1.3rem auto",
    fontSize: "0.95rem",
    fontWeight: "bold",
    marginTop: "1rem",
  },
  optionsCntr: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginRight: "1.4%",
  },
  optionBtn: {
    flexBasis: "25%",
  },
  optionIcon: {
    fill: "#ff9b22",
    background: "#ffe3ae",
    width: "2.8rem",
    height: "2.8rem",
    padding: "11px",
    borderRadius: "50%",
  },
  optionTxt: {
    textTransform: "capitalize",
    fontSize: "0.75rem",
    fontFamily: "'Proxima Nova'",
  },
  checkoutCntr: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
    marginTop: "1.4rem",
  },
  focusBorder: {
    width: "10%",
    maxWidth: "65px",
    minWidth: "50px",
    padding: "15px 10px",
    textAlign: "center",
    border: "1px solid lightgray",
    fontSize: "1.1rem",
    fontWeight: "500",
    borderRadius: "8px",
    margin: "10px 0.85rem",
    outline: "none",
    "&:focus": {
      outline: "2px solid black",
    },
  },
  checkoutBtn: {
    textAlign: "center",
    textTransform: "capitalize",
    padding: "8px",
    width: "90%",
    color: "white",
    background: "#007Bff",
    margin: "8px",
    fontSize: "1rem",
    fontWeight: "600",
    borderRadius: "12px",
  },
  passcodeCntr: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 1rem",
    margin: "1rem",
    border: "1px solid #d8d8d8",
    borderRadius: "10px",
    fontFamily: "'Proxima Nova'",
  },
  pinTxt: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "1rem",
    fontFamily: "'Proxima Nova'",
    fontWeight: "600",
  },
  pinIcn: {
    width: "1rem",
    height: "1.2rem",
    marginRight: "5px",
  },
  pinCntr: {
    flexBasis: "40%",
    display: "flex",
    justifyContent: "space-around",
  },
  pin: {
    width: "1.0rem",
    height: "1.8rem",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "#eaeaea",
    borderRadius: "5px",
    fontSize: "1rem",
    fontWeight: "600",
  },
  resendCntr: {
    marginTop: "10px",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    color: "#0768d0",
  },
  resendEdtIcn: {
    width: "1rem",
    verticalAlign: "middle",
    height: "1rem",
    marginRight: "3px",
  },
}));
