export const USER_AUTH = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNUP_LOADING: "SIGNUP_LOADING",
};

export const LOGIN_AUTH = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_LOADING: "LOGIN_LOADING",
  SOCKET_CONNECTION: "SOCKET_CONNECTION",
};

export const LOGOUT_AUTH = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  LOGOUT_LOADING: "LOGOUT_LOADING",
};

export const USER_PROFILE = {
  USER_GET_PROFILE_REQUEST: "USER_GET_PROFILE_REQUEST",
  USER_GET_PROFILE_SUCCESS: "USER_GET_PROFILE_SUCCESS",
  USER_GET_PROFILE_ERROR: "USER_GET_PROFILE_ERROR",
  USER_GET_PROFILE_LOADING: "USER_GET_PROFILE_LOADING",

  USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  USER_UPDATE_PROFILE_ERROR: "USER_UPDATE_PROFILE_ERROR",
  USER_UPDATE_PROFILE_LOADING: "USER_UPDATE_PROFILE_LOADING",
};
export const WALLET = {
  GET_WALLET_REQUEST: "GET_WALLET_REQUEST",
  GET_WALLET_REQUEST1: "GET_WALLET_REQUEST1",
  GET_WALLET_SUCCESS: "GET_WALLET_SUCCESS",
  GET_WALLET_ERROR: "GET_WALLET_ERROR",
  GET_WALLET_LOADING: "GET_WALLET_LOADING",

  UPDATE_WALLET_REQUEST: "UPDATE_WALLET_REQUEST",
  UPDATE_WALLET_SUCCESS: "UPDATE_WALLET_SUCCESS",
  UPDATE_WALLET_ERROR: "UPDATE_WALLET_ERROR",
  UPDATE_WALLET_LOADING: "UPDATE_WALLET_LOADING",

  USER_BUY_CHIPS_REQUEST: "USER_BUY_CHIPS_REQUEST",
  USER_BUY_CHIPS_SUCCESS: "USER_BUY_CHIPS_SUCCESS",
  USER_BUY_CHIPS_LOADING: "USER_BUY_CHIPS_LOADING",
  USER_BUY_CHIPS_ERROR: "USER_BUY_CHIPS_ERROR",

  USER_SELL_CHIPS_REQUEST: "USER_SELL_CHIPS_REQUEST",
  USER_SELL_CHIPS_SUCCESS: "USER_SELL_CHIPS_SUCCESS",
  USER_SELL_CHIPS_LOADING: "USER_SELL_CHIPS_LOADING",
  USER_SELL_CHIPS_ERROR: "USER_SELL_CHIPS_ERROR",
};
