name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to SSH
          key: ${{ secrets.SSH_KEY }} # Private or public key of the serve
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo 'Deployment successful to DigitalOcean'
