name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0
      
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to SSH
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            git clone git@github.com:practice5610/frontend_ludo.git
            cd frontend_ludo
            npm install
            npm run build
            echo 'Deployment successful to DigitalOcean'
