name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Load Environment Variables
        run: npm install dotenv --global
      
      - name: Build React App
        run: |
          source .env
          npm run build
      
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Your deployment script here
