name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh
          key: ${{secrets.SSH_KEY}} # Private or public key of the ser
          username: ${{secrets.SSH_USERNAME}}
          

          script: |
            git clone git@github.com:practice5610/frontend_ludo.git
            cd frontend_ludo
            npm install
            npm run build
            echo 'Deployment successful to DigitalOcean'
