name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build the React app
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/your_domain/html
            rm -rf * # Remove existing files in the deployment directory (optional)
            cp -r $GITHUB_WORKSPACE/build/* .
            echo 'Deployment successful to your server'
