name: Build & Deploy
on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.STAG_HOST}} # IP address of the server you wish to ssh
          key: ${{secrets.STAG_KEY}} 
          username: root
          script: |
            git clone git@github.com:practice5610/frontend_ludo.git
            cd frontend_ludo
            cp -R build /var/www/your_domain/html
            sudo service nginx restart
            sudo systemctl reload nginx
            echo 'Production Deployment successful to DigitalOcean'
